evap/grades/urls.py
from django.urls import path

from evap.grades import views


app_name = "grades"

urlpatterns = [
    path("", views.index, name="index"),

    path("download/<int:grade_document_id>", views.download_grades, name="download_grades"),
    path("semester/<int:semester_id>", views.semester_view, name="semester_view"),
    path("semester/<int:semester_id>/course/<int:course_id>", views.course_view, name="course_view"),
    path("semester/<int:semester_id>/course/<int:course_id>/upload", views.upload_grades, name="upload_grades"),
    path("semester/<int:semester_id>/course/<int:course_id>/edit/<int:grade_document_id>", views.edit_grades, name="edit_grades"),

    path("delete_grades", views.delete_grades, name="delete_grades"),
    path("toggle_no_grades", views.toggle_no_grades, name="toggle_no_grades"),
]

evap/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import include, path
import django.contrib.auth.views


urlpatterns = [
    path("", include('evap.evaluation.urls')),
    path("staff/", include('evap.staff.urls')),
    path("results/", include('evap.results.urls')),
    path("student/", include('evap.student.urls')),
    path("contributor/", include('evap.contributor.urls')),
    path("rewards/", include('evap.rewards.urls')),
    path("grades/", include('evap.grades.urls')),

    path("logout", django.contrib.auth.views.LogoutView.as_view(next_page="/"), name="django-auth-logout"),
    url(r'^oidc/', include('mozilla_django_oidc.urls')),
]

if settings.DEBUG and settings.ENABLE_DEBUG_TOOLBAR:
    # pylint does not correctly evaluate this if, so it will raise an import-error on
    # travis and a useless-suppression on a vagrant setup. Ignore both cases.
    import debug_toolbar  # pylint: disable=import-error, useless-suppression
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

grades/urls.py
from django.conf.urls import url

from evap.grades.views import *


app_name = "grades"

urlpatterns = [
    url(r"^$", index, name="index"),

    url(r"^download/(\d+)$", download_grades, name="download_grades"),
    url(r"^semester/(\d+)$", semester_view, name="semester_view"),
    url(r"^semester/(\d+)/course/(\d+)$", course_view, name="course_view"),
    url(r"^semester/(\d+)/course/(\d+)/upload$", upload_grades, name="upload_grades"),
    url(r"^semester/(\d+)/course/(\d+)/edit/(\d+)$", edit_grades, name="edit_grades"),

    url(r"^delete_grades$", delete_grades, name="delete_grades"),
    url(r"^toggle_no_grades$", toggle_no_grades, name="toggle_no_grades"),

    url(r"^semester/(\d+)/grade_activation/(\w+)$", semester_grade_activation, name="semester_grade_activation"),
]

urls.py
from django.conf import settings
from django.conf.urls import include, url
import django.views.static
import django.contrib.auth.views

from django.contrib import admin
admin.autodiscover()


urlpatterns = [
    url(r"^", include('evap.evaluation.urls')),
    url(r"^staff/", include('evap.staff.urls')),
    url(r"^results/", include('evap.results.urls')),
    url(r"^student/", include('evap.student.urls')),
    url(r"^contributor/", include('evap.contributor.urls')),
    url(r"^rewards/", include('evap.rewards.urls')),
    url(r"^grades/", include('evap.grades.urls')),

    url(r"^logout$", django.contrib.auth.views.logout, {'next_page': "/"}, name="django-auth-logout"),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r"^admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT})]

if settings.DEBUG and settings.ENABLE_DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]

evap/grades/models.py
import os

from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import pre_delete, pre_save
from django.dispatch.dispatcher import receiver

from evap.evaluation.models import Course
from evap.evaluation.tools import translate


def helper_upload_path(instance, filename):
    return "grades/{}/{}".format(instance.course.id, filename)


class GradeDocument(models.Model):
    course = models.ForeignKey(Course, models.PROTECT, related_name='grade_documents', verbose_name=_("course"))
    file = models.FileField(upload_to=helper_upload_path, verbose_name=_("File"))  # upload_to="grades/{}/".format(course.id),

    class Type(models.TextChoices):
        MIDTERM_GRADES = 'MID', _('midterm grades')
        FINAL_GRADES = 'FIN', _('final grades')

    type = models.CharField(max_length=3, choices=Type.choices, verbose_name=_('grade type'), default=Type.MIDTERM_GRADES)

    description_de = models.CharField(max_length=255, verbose_name=_("description (german)"))
    description_en = models.CharField(max_length=255, verbose_name=_("description (english)"))
    description = translate(en='description_en', de='description_de')

    last_modified_time = models.DateTimeField(auto_now=True, verbose_name=_("Created"))
    last_modified_user = models.ForeignKey(settings.AUTH_USER_MODEL, models.SET_NULL, related_name="grades_last_modified_user+", null=True, blank=True)

    class Meta:
        verbose_name = _("Grade Document")
        verbose_name_plural = _("Grade Documents")
        unique_together = (
            ('course', 'description_de'),
            ('course', 'description_en')
        )

    def __str__(self):
        return self.description

    def filename(self):
        return os.path.basename(self.file.name)


@receiver(pre_delete, sender=GradeDocument)
def delete_file_pre_delete(instance, **_kwargs):
    if instance.file:
        instance.file.delete(False)


# Changing should lead to the removal of the old file
@receiver(pre_save, sender=GradeDocument)
def delete_file_pre_save(instance, **_kwargs):
    if not instance.pk:  # We do not want to trigger document creation
        return
    try:
        oldFile = GradeDocument.objects.get(pk=instance.pk).file
    except GradeDocument.DoesNotExist:
        return
    newFile = instance.file
    if not oldFile == newFile:
        oldFile.delete(False)

evap/grades/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError

from evap.grades.models import GradeDocument


class GradeDocumentFileWidget(forms.widgets.ClearableFileInput):
    template_name = 'grade_document_file_widget.html'


class GradeDocumentForm(forms.ModelForm):
    last_modified_time_2 = forms.DateTimeField(label=_("Last modified"), required=False, localize=True, disabled=True)
    last_modified_user_2 = forms.CharField(label=_("Last modified by"), required=False, disabled=True)

    class Meta:
        model = GradeDocument
        fields = ('description_de', 'description_en', 'file', 'last_modified_time_2', 'last_modified_user_2')
        widgets = {'file': GradeDocumentFileWidget()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance.last_modified_user:
            self.fields['last_modified_time_2'].initial = self.instance.last_modified_time
            self.fields['last_modified_user_2'].initial = self.instance.last_modified_user.full_name
        else:
            self.fields['last_modified_time_2'].widget = forms.HiddenInput()
            self.fields['last_modified_user_2'].widget = forms.HiddenInput()

    def clean_description_de(self):
        description_de = self.cleaned_data.get('description_de')
        if GradeDocument.objects.filter(course=self.instance.course, description_de=description_de).exclude(id=self.instance.id).exists():
            raise ValidationError(_("This description for a grade document was already used for this course."))
        return description_de

    def clean_description_en(self):
        description_en = self.cleaned_data.get('description_en')
        if GradeDocument.objects.filter(course=self.instance.course, description_en=description_en).exclude(id=self.instance.id).exists():
            raise ValidationError(_("This description for a grade document was already used for this course."))
        return description_en

    def save(self, *args, modifying_user, **kwargs):  # pylint: disable=arguments-differ
        self.instance.last_modified_user = modifying_user
        super().save(*args, **kwargs)

grades/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError

from evap.grades.models import GradeDocument


class GradeDocumentForm(forms.ModelForm):
    # see CourseForm (staff/forms.py) for details, why the following two fields are needed
    last_modified_time_2 = forms.DateTimeField(label=_("Last modified"), required=False, localize=True, disabled=True)
    last_modified_user_2 = forms.CharField(label=_("Last modified by"), required=False, disabled=True)

    class Meta:
        model = GradeDocument
        fields = ('description_de', 'description_en', 'file', 'last_modified_time_2', 'last_modified_user_2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance.last_modified_user:
            self.fields['last_modified_time_2'].initial = self.instance.last_modified_time
            self.fields['last_modified_user_2'].initial = self.instance.last_modified_user.full_name
        else:
            self.fields['last_modified_time_2'].widget = forms.HiddenInput()
            self.fields['last_modified_user_2'].widget = forms.HiddenInput()

    def clean_description_de(self):
        description_de = self.cleaned_data.get('description_de')
        if GradeDocument.objects.filter(course=self.instance.course, description_de=description_de).exclude(id=self.instance.id).exists():
            raise ValidationError(_("This description for a grade document was already used for this course."))
        return description_de

    def clean_description_en(self):
        description_en = self.cleaned_data.get('description_en')
        if GradeDocument.objects.filter(course=self.instance.course, description_en=description_en).exclude(id=self.instance.id).exists():
            raise ValidationError(_("This description for a grade document was already used for this course."))
        return description_en

    def save(self, modifying_user, *args, **kwargs):
        self.instance.last_modified_user = modifying_user
        super().save(*args, **kwargs)

evap/grades/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.conf import settings
from django.utils.translation import gettext as _
from django.http import HttpResponse
from django.views.decorators.http import require_POST, require_GET

from django_sendfile import sendfile

from evap.evaluation.auth import grade_publisher_required, grade_downloader_required, grade_publisher_or_manager_required
from evap.evaluation.models import Course, Semester, EmailTemplate
from evap.grades.models import GradeDocument
from evap.grades.forms import GradeDocumentForm


@grade_publisher_required
def index(request):
    template_data = dict(
        semesters=Semester.objects.filter(grade_documents_are_deleted=False),
        disable_breadcrumb_grades=True,
    )
    return render(request, "grades_index.html", template_data)


def prefetch_data(courses):
    courses = courses.prefetch_related("degrees", "responsibles")

    course_data = []
    for course in courses:
        course_data.append((
            course,
            course.midterm_grade_documents.count(),
            course.final_grade_documents.count()
        ))

    return course_data


@grade_publisher_required
def semester_view(request, semester_id):
    semester = get_object_or_404(Semester, id=semester_id)
    if semester.grade_documents_are_deleted:
        raise PermissionDenied

    courses = (semester.courses
        .filter(evaluations__wait_for_grade_upload_before_publishing=True)
        .exclude(evaluations__state='new')
        .distinct())
    courses = prefetch_data(courses)

    template_data = dict(
        semester=semester,
        courses=courses,
        disable_if_archived="disabled" if semester.grade_documents_are_deleted else "",
        disable_breadcrumb_semester=True,
    )
    return render(request, "grades_semester_view.html", template_data)


@grade_publisher_or_manager_required
def course_view(request, semester_id, course_id):
    semester = get_object_or_404(Semester, id=semester_id)
    if semester.grade_documents_are_deleted:
        raise PermissionDenied
    course = get_object_or_404(Course, id=course_id, semester=semester)

    template_data = dict(
        semester=semester,
        course=course,
        grade_documents=course.grade_documents.all(),
        disable_if_archived="disabled" if semester.grade_documents_are_deleted else "",
        disable_breadcrumb_course=True,
    )
    return render(request, "grades_course_view.html", template_data)


def on_grading_process_finished(course):
    evaluations = course.evaluations.all()
    if all(evaluation.state == 'reviewed' for evaluation in evaluations):
        for evaluation in evaluations:
            assert evaluation.grading_process_is_finished
        for evaluation in evaluations:
            evaluation.publish()
            evaluation.save()

        EmailTemplate.send_participant_publish_notifications(evaluations)
        EmailTemplate.send_contributor_publish_notifications(evaluations)


@grade_publisher_required
def upload_grades(request, semester_id, course_id):
    semester = get_object_or_404(Semester, id=semester_id)
    if semester.grade_documents_are_deleted:
        raise PermissionDenied
    course = get_object_or_404(Course, id=course_id, semester=semester)

    final_grades = request.GET.get('final') == 'true'  # if parameter is not given, assume midterm grades

    grade_document = GradeDocument(course=course)
    if final_grades:
        grade_document.type = GradeDocument.Type.FINAL_GRADES
        grade_document.description_en = settings.DEFAULT_FINAL_GRADES_DESCRIPTION_EN
        grade_document.description_de = settings.DEFAULT_FINAL_GRADES_DESCRIPTION_DE
    else:
        grade_document.type = GradeDocument.Type.MIDTERM_GRADES
        grade_document.description_en = settings.DEFAULT_MIDTERM_GRADES_DESCRIPTION_EN
        grade_document.description_de = settings.DEFAULT_MIDTERM_GRADES_DESCRIPTION_DE

    form = GradeDocumentForm(request.POST or None, request.FILES or None, instance=grade_document)

    if form.is_valid():
        form.save(modifying_user=request.user)

        if final_grades:
            on_grading_process_finished(course)

        messages.success(request, _("Successfully uploaded grades."))
        return redirect('grades:course_view', semester.id, course.id)

    template_data = dict(
        semester=semester,
        course=course,
        form=form,
        final_grades=final_grades,
        show_automated_publishing_info=final_grades,
    )
    return render(request, "grades_upload_form.html", template_data)


@require_POST
@grade_publisher_required
def toggle_no_grades(request):
    course_id = request.POST.get("course_id")
    course = get_object_or_404(Course, id=course_id)
    if course.semester.grade_documents_are_deleted:
        raise PermissionDenied

    course.gets_no_grade_documents = not course.gets_no_grade_documents
    course.save()

    if course.gets_no_grade_documents:
        on_grading_process_finished(course)

    return HttpResponse()  # 200 OK


@require_GET
@grade_downloader_required
def download_grades(request, grade_document_id):
    grade_document = get_object_or_404(GradeDocument, id=grade_document_id)
    if grade_document.course.semester.grade_documents_are_deleted:
        raise PermissionDenied

    return sendfile(request, grade_document.file.path, attachment=True, attachment_filename=grade_document.filename())


@grade_publisher_required
def edit_grades(request, semester_id, course_id, grade_document_id):
    semester = get_object_or_404(Semester, id=semester_id)
    if semester.grade_documents_are_deleted:
        raise PermissionDenied
    course = get_object_or_404(Course, id=course_id, semester=semester)
    grade_document = get_object_or_404(GradeDocument, id=grade_document_id, course=course)

    form = GradeDocumentForm(request.POST or None, request.FILES or None, instance=grade_document)

    if form.is_valid():
        form.save(modifying_user=request.user)
        messages.success(request, _("Successfully updated grades."))
        return redirect('grades:course_view', semester.id, course.id)

    template_data = dict(
        semester=semester,
        course=course,
        form=form,
        show_automated_publishing_info=False,
    )
    return render(request, "grades_upload_form.html", template_data)


@require_POST
@grade_publisher_required
def delete_grades(request):
    grade_document_id = request.POST.get("grade_document_id")
    grade_document = get_object_or_404(GradeDocument, id=grade_document_id)

    grade_document.delete()
    return HttpResponse()  # 200 OK

evap/grades/templates/grade_document_file_widget.html
{# based on django/forms/widgets/clearable_file_input.html #}
{% if widget.is_initial %}
    {{ widget.initial_text }}: <a href="{% url 'grades:download_grades' widget.value.instance.id %}">{{ widget.value.instance.filename }}</a>
    <br /> {{ widget.input_text }}:
{% endif %}
<input type="{{ widget.type }}" name="{{ widget.name }}" {% include 'django/forms/widgets/attrs.html' %} />

evap/grades/templates/grades_base.html
{% extends 'base.html' %}

{% block title %}{% trans 'Grade publishing' %} - {{ block.super }}{% endblock %}

{% block breadcrumb_bar %}
    <ul class="breadcrumb">
        {% block breadcrumb %}
            {% if disable_breadcrumb_grades or not user.is_grade_publisher %}
                <li class="breadcrumb-item">{% trans 'Grade publishing' %}</li>
            {% else %}
                <li class="breadcrumb-item"><a href="{% url 'grades:index' %}">{% trans 'Grade publishing' %}</a></li>
            {% endif %}
        {% endblock %}
    </ul>
{% endblock %}

evap/grades/templates/grades_course_base.html
{% extends 'grades_semester_base.html' %}

{% block title %}{{ course.name }} - {{ block.super }}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    {% if course %}
        {% if disable_breadcrumb_course %}
            <li class="breadcrumb-item">{{ course.name }}</li>
        {% else %}
            <li class="breadcrumb-item"><a href="{% url 'grades:course_view' semester.id course.id %}">{{ course.name }}</a></li>
        {% endif %}
    {% endif %}
{% endblock %}

evap/grades/templates/grades_course_view.html
{% extends 'grades_course_base.html' %}

{% block content %}
    {{ block.super }}

    <h3 class="mb-3">{{ course.name }} ({{ semester.name }})</h3>

    <div class="card mb-3">
        <div class="card-header">
            {% trans 'Uploaded grade documents' %}
        </div>
        <div class="card-body">
            {% if grade_documents %}
                <table class="table table-striped table-vertically-aligned">
                    <thead>
                        <tr>
                            <th style="width: 40%">{% trans 'Description' %}</th>
                            <th style="width: 20%">{% trans 'Type' %}</th>
                            <th style="width: 25%">{% trans 'Last edited' %}</th>
                            <th style="width: 15%">{% trans 'Actions' %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for grade_document in grade_documents %}
                            <tr id="grade_document-row-{{ grade_document.id }}">
                                <td>{{ grade_document.description }}</td>
                                <td>{{ grade_document.get_type_display }}</td>
                                <td>{{ grade_document.last_modified_time }}, {% trans 'by' %} {{ grade_document.last_modified_user }}</td>
                                <td>
                                    <a href="{% url 'grades:download_grades' grade_document.id %}" class="btn btn-sm btn-light" data-toggle="tooltip" data-placement="top" title="{% trans 'Download' %}"><span class="fas fa-download"></span></a>
                                    {% if user.is_grade_publisher %}
                                        <a href="{% url 'grades:edit_grades' semester.id course.id grade_document.id %}" class="btn btn-sm btn-light" data-toggle="tooltip" data-placement="top" title="{% trans 'Edit' %}"><span class="fas fa-pencil-alt"></span></a>
                                        <button type="button" {{ disable_if_archived }} onclick="deleteGradedocumentModalShow({{ grade_document.id }}, '{{ grade_document.description|escapejs }}');" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="{% trans 'Delete' %}">
                                            <span class="fas fa-trash"></span>
                                        </button>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <span class="font-italic">{% trans 'No grade documents have been uploaded yet' %}</span>
            {% endif %}
        </div>
    </div>
    {% if user.is_grade_publisher %}
        <a href="{% url 'grades:upload_grades' semester.id course.id %}" class="btn btn-dark {{ disable_if_archived }}">{% trans 'Upload new midterm grades' %}</a>
        <a href="{% url 'grades:upload_grades' semester.id course.id %}?final=true" class="btn btn-dark {{ disable_if_archived }}">{% trans 'Upload new final grades' %}</a>
    {% endif %}
{% endblock %}

{% block modals %}
    {{ block.super }}
    {% trans 'Delete grade document' as title %}
    {% trans 'Do you really want to delete the grade document <strong id="data-label"></strong>?' as question %}
    {% trans 'Delete grade document' as action_text %}
    {% include 'confirmation_modal.html' with modal_id='deleteGradedocumentModal' title=title question=question action_text=action_text btn_type='danger' %}
    <script type="text/javascript">
        function deleteGradedocumentModalAction(dataId) {
            $.ajax({
                type: "POST",
                url: "{% url 'grades:delete_grades' %}",
                data: {"grade_document_id": dataId},
                success: function(){ $('#grade_document-row-'+dataId).hide('slow', function(){ $('#grade_document-row-'+dataId).remove(); }); },
                error: function(){ window.alert("{% trans 'The server is not responding.' %}"); }
            });
        };
    </script>
{% endblock %}

evap/grades/templates/grades_evaluation_view.html
{% extends 'grades_evaluation_base.html' %}

{% block content %}
    {{ block.super }}

    <h3 class="mb-3">{{ evaluation.name }} ({{ semester.name }})</h3>

    <div class="card mb-3">
        <div class="card-header">
            {% trans 'Uploaded grade documents' %}
        </div>
        <div class="card-body">
            {% if grade_documents %}
                <table class="table table-striped vertically-aligned">
                    <thead>
                        <tr>
                            <th style="width: 40%">{% trans 'Description' %}</th>
                            <th style="width: 20%">{% trans 'Type' %}</th>
                            <th style="width: 25%">{% trans 'Last edited' %}</th>
                            <th style="width: 15%">{% trans 'Actions' %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for grade_document in grade_documents %}
                            <tr id="grade_document-row-{{ grade_document.id }}">
                                <td>{{ grade_document.description }}</td>
                                <td>{{ grade_document.get_type_display }}</td>
                                <td>{{ grade_document.last_modified_time }}, {% trans 'by' %} {{ grade_document.last_modified_user }}</td>
                                <td>
                                    <a href="{% url 'grades:download_grades' grade_document.id %}" class="btn btn-sm btn-light" data-toggle="tooltip" data-placement="top" title="{% trans 'Download' %}"><span class="fas fa-download"></span></a>
                                    {% if user.is_grade_publisher %}
                                        <a href="{% url 'grades:edit_grades' semester.id evaluation.id grade_document.id %}" class="btn btn-sm btn-light" data-toggle="tooltip" data-placement="top" title="{% trans 'Edit' %}"><span class="fas fa-pencil-alt"></span></a>
                                        <a role="button" onclick="deleteGradedocumentModalShow({{ grade_document.id }}, '{{ grade_document.description|escapejs }}');" class="btn btn-sm btn-danger {{ disable_if_archived }}" data-toggle="tooltip" data-placement="top" title="{% trans 'Delete' %}"><span class="fas fa-trash"></span></a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <i>{% trans 'No grade documents have been uploaded yet' %}</i>
            {% endif %}
        </div>
    </div>
    {% if user.is_grade_publisher %}
        <a href="{% url 'grades:upload_grades' semester.id evaluation.id %}" class="btn btn-dark {{ disable_if_archived }}">{% trans 'Upload new midterm grades' %}</a>
        <a href="{% url 'grades:upload_grades' semester.id evaluation.id %}?final=true" class="btn btn-dark {{ disable_if_archived }}">{% trans 'Upload new final grades' %}</a>
    {% endif %}
{% endblock %}

{% block modals %}
    {{ block.super }}
    {% trans 'Delete grade document' as title %}
    {% trans 'Do you really want to delete the grade document <strong id="data-label"></strong>?' as question %}
    {% trans 'Delete grade document' as action_text %}
    {% include 'confirmation_modal.html' with modal_id='deleteGradedocumentModal' title=title question=question action_text=action_text btn_type='danger' %}
    <script type="text/javascript">
        function deleteGradedocumentModalAction(dataId) {
            $.ajax({
                type: "POST",
                url: "{% url 'grades:delete_grades' %}",
                data: {"grade_document_id": dataId},
                success: function(){ $('#grade_document-row-'+dataId).hide('slow', function(){ $('#grade_document-row-'+dataId).remove(); }); },
                error: function(){ window.alert("{% trans 'The server is not responding.' %}"); }
            });
        };
    </script>
{% endblock %}

evap/grades/templates/grades_index.html
{% extends 'grades_base.html' %}

{% block content %}
    <h3>{% trans 'Semesters' %}</h3>
    <div class="card mb-3">
        <div class="card-body">
            {% if semesters %}
                <ul>
                {% for semester in semesters %}
                    <li><a href="{% url 'grades:semester_view' semester.id %}">{{ semester.name }}</a></li>
                {% endfor %}
                </ul>
            {% else %}
                {% trans 'There are no semesters yet.' %}
            {% endif %}
        </div>
    </div>
{% endblock %}

evap/grades/templates/grades_semester_base.html
{% extends 'grades_base.html' %}

{% load evaluation_filters %}

{% block title %}{{ semester.name }} - {{ block.super }}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    {% if semester %}
        {% if disable_breadcrumb_semester or not user.is_grade_publisher %}
            <li class="breadcrumb-item">{{ semester.name }}</li>
        {% else %}
            <li class="breadcrumb-item"><a href="{% url 'grades:semester_view' semester.id %}">{{ semester.name }}</a></li>
        {% endif %}
    {% endif %}
{% endblock %}

evap/grades/templates/grades_upload_form.html
{% extends 'grades_course_base.html' %}

{% block breadcrumb %}
    {{ block.super }}
    <li class="breadcrumb-item">{% trans "Upload document" %}</li>
{% endblock %}

{% block content %}
    {{ block.super }}

    {% if show_automated_publishing_info %}
        <div class="callout callout-info">
            <b>{% trans 'Automated publishing' %}</b><br />
            {% blocktrans %}After this file with final grades was uploaded, the evaluation results will be published automatically once the evaluation ends. If the evaluation has already ended, it will be published immediately. All contributors and participants will receive an email informing them about the published evaluation results and the available grade file document.{% endblocktrans %}
        </div>
    {% endif %}

    <h3 class="mb-3">
        {% if final_grades %}
            {% blocktrans with course=course.name semester=semester.name %}Upload final grades for {{ course }} ({{ semester }}){% endblocktrans %}
        {% else %}
            {% blocktrans with course=course.name semester=semester.name %}Upload midterm grades for {{ course }} ({{ semester }}){% endblocktrans %}
        {% endif %}
    </h3>
    <form method="POST" class="form-horizontal" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card mb-3">
            <div class="card-body">
                {% include 'bootstrap_form.html' with form=form %}
            </div>
        </div>
        <div class="card card-submit-area text-center mb-3">
            <div class="card-body">
                <button type="submit" class="btn btn-primary">{% trans 'Upload grades' %}</button>
            </div>
        </div>
    </form>
{% endblock %}