evap/rewards/urls.py
from django.urls import path

from evap.rewards import views


app_name = "rewards"

urlpatterns = [
    path("", views.index, name="index"),

    path("reward_point_redemption_events/", views.reward_point_redemption_events, name="reward_point_redemption_events"),
    path("reward_point_redemption_event/create", views.reward_point_redemption_event_create, name="reward_point_redemption_event_create"),
    path("reward_point_redemption_event/<int:event_id>/edit", views.reward_point_redemption_event_edit, name="reward_point_redemption_event_edit"),
    path("reward_point_redemption_event/<int:event_id>/export", views.reward_point_redemption_event_export, name="reward_point_redemption_event_export"),
    path("reward_point_redemption_event/delete", views.reward_point_redemption_event_delete, name="reward_point_redemption_event_delete"),

    path("reward_semester_activation/<int:semester_id>/<str:active>", views.semester_activation, name="semester_activation"),
]

evap/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import include, path
import django.contrib.auth.views


urlpatterns = [
    path("", include('evap.evaluation.urls')),
    path("staff/", include('evap.staff.urls')),
    path("results/", include('evap.results.urls')),
    path("student/", include('evap.student.urls')),
    path("contributor/", include('evap.contributor.urls')),
    path("rewards/", include('evap.rewards.urls')),
    path("grades/", include('evap.grades.urls')),

    path("logout", django.contrib.auth.views.LogoutView.as_view(next_page="/"), name="django-auth-logout"),
    url(r'^oidc/', include('mozilla_django_oidc.urls')),
]

if settings.DEBUG and settings.ENABLE_DEBUG_TOOLBAR:
    # pylint does not correctly evaluate this if, so it will raise an import-error on
    # travis and a useless-suppression on a vagrant setup. Ignore both cases.
    import debug_toolbar  # pylint: disable=import-error, useless-suppression
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

rewards/urls.py
from django.conf.urls import url

from evap.rewards.views import *


app_name = "rewards"

urlpatterns = [
    url(r"^$", index, name="index"),

    url(r"^reward_point_redemption_events/$", reward_point_redemption_events, name="reward_point_redemption_events"),
    url(r"^reward_point_redemption_event/create$", reward_point_redemption_event_create, name="reward_point_redemption_event_create"),
    url(r"^reward_point_redemption_event/(\d+)/edit$", reward_point_redemption_event_edit, name="reward_point_redemption_event_edit"),
    url(r"^reward_point_redemption_event/(\d+)/export$", reward_point_redemption_event_export, name="reward_point_redemption_event_export"),
    url(r"^reward_point_redemption_event/delete$", reward_point_redemption_event_delete, name="reward_point_redemption_event_delete"),

    url(r"^reward_semester_activation/(\d+)/(\w+)$", semester_activation, name="semester_activation"),
]

urls.py
from django.conf import settings
from django.conf.urls import include, url
import django.views.static
import django.contrib.auth.views

from django.contrib import admin
admin.autodiscover()


urlpatterns = [
    url(r"^", include('evap.evaluation.urls')),
    url(r"^staff/", include('evap.staff.urls')),
    url(r"^results/", include('evap.results.urls')),
    url(r"^student/", include('evap.student.urls')),
    url(r"^contributor/", include('evap.contributor.urls')),
    url(r"^rewards/", include('evap.rewards.urls')),
    url(r"^grades/", include('evap.grades.urls')),

    url(r"^logout$", django.contrib.auth.views.logout, {'next_page': "/"}, name="django-auth-logout"),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r"^admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT})]

if settings.DEBUG and settings.ENABLE_DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]

rewards/models.py
from collections import OrderedDict

from django.utils.translation import ugettext_lazy as _
from django.db import models


class NoPointsSelected(Exception):
    """An attempt has been made to redeem <= 0 points."""
    pass


class NotEnoughPoints(Exception):
    """An attempt has been made to redeem more points than available."""
    pass


class RewardPointRedemptionEvent(models.Model):
    name = models.CharField(max_length=1024, verbose_name=_("event name"))
    date = models.DateField(verbose_name=_("event date"))
    redeem_end_date = models.DateField(verbose_name=_("redemption end date"))

    @property
    def can_delete(self):
        if RewardPointRedemption.objects.filter(event=self).exists():
            return False
        return True

    def redemptions_by_user(self):
        redemptions = self.reward_point_redemptions.order_by('user_profile')
        redemptions_dict = OrderedDict()
        for redemption in redemptions:
            if redemption.user_profile not in redemptions_dict:
                redemptions_dict[redemption.user_profile] = 0
            redemptions_dict[redemption.user_profile] += redemption.value
        return redemptions_dict


class RewardPointGranting(models.Model):
    user_profile = models.ForeignKey('evaluation.UserProfile', models.CASCADE, related_name="reward_point_grantings")
    semester = models.ForeignKey('evaluation.Semester', models.PROTECT, related_name="reward_point_grantings")
    granting_time = models.DateTimeField(verbose_name=_("granting time"), auto_now_add=True)
    value = models.IntegerField(verbose_name=_("value"), default=0)


class RewardPointRedemption(models.Model):
    user_profile = models.ForeignKey('evaluation.UserProfile', models.CASCADE, related_name="reward_point_redemptions")
    redemption_time = models.DateTimeField(verbose_name=_("redemption time"), auto_now_add=True)
    value = models.IntegerField(verbose_name=_("value"), default=0)
    event = models.ForeignKey(RewardPointRedemptionEvent, models.PROTECT, related_name="reward_point_redemptions")


class SemesterActivation(models.Model):
    semester = models.OneToOneField('evaluation.Semester', models.CASCADE, related_name='rewards_active')
    is_active = models.BooleanField(default=False)

evap/rewards/forms.py
from django import forms

from evap.rewards.models import RewardPointRedemptionEvent


class RewardPointRedemptionEventForm(forms.ModelForm):
    class Meta:
        model = RewardPointRedemptionEvent
        fields = ('name', 'date', 'redeem_end_date')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date'].localize = True
        self.fields['redeem_end_date'].localize = True

rewards/forms.py
from django import forms

from evap.rewards.models import RewardPointRedemptionEvent


class RewardPointRedemptionEventForm(forms.ModelForm):
    class Meta:
        model = RewardPointRedemptionEvent
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date'].localize = True
        self.fields['redeem_end_date'].localize = True

evap/rewards/views.py
from datetime import datetime

from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext as _
from django.utils.translation import get_language
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.core.exceptions import SuspiciousOperation

from evap.evaluation.auth import reward_user_required, manager_required
from evap.evaluation.models import Semester
from evap.evaluation.tools import FileResponse

from evap.staff.views import semester_view

from evap.rewards.models import RewardPointGranting, RewardPointRedemption, RewardPointRedemptionEvent, \
                                SemesterActivation, NoPointsSelected, NotEnoughPoints, RedemptionEventExpired
from evap.rewards.tools import save_redemptions, reward_points_of_user
from evap.rewards.forms import RewardPointRedemptionEventForm
from evap.rewards.exporters import RewardsExporter


@reward_user_required
def index(request):
    if request.method == 'POST':
        redemptions = {}
        for key, value in request.POST.items():
            if key.startswith('points-'):
                event_id = int(key.rpartition('-')[2])
                redemptions[event_id] = int(value)

        try:
            save_redemptions(request, redemptions)
            messages.success(request, _("You successfully redeemed your points."))
        except (NoPointsSelected, NotEnoughPoints, RedemptionEventExpired) as error:
            messages.warning(request, error)

    total_points_available = reward_points_of_user(request.user)
    reward_point_grantings = RewardPointGranting.objects.filter(user_profile=request.user)
    reward_point_redemptions = RewardPointRedemption.objects.filter(user_profile=request.user)
    events = RewardPointRedemptionEvent.objects.filter(redeem_end_date__gte=datetime.now()).order_by('date')

    reward_point_actions = []
    for granting in reward_point_grantings:
        reward_point_actions.append((granting.granting_time, _('Reward for') + ' ' + granting.semester.name, granting.value, ''))
    for redemption in reward_point_redemptions:
        reward_point_actions.append((redemption.redemption_time, redemption.event.name, '', redemption.value))

    reward_point_actions.sort(key=lambda action: action[0], reverse=True)

    template_data = dict(
            reward_point_actions=reward_point_actions,
            total_points_available=total_points_available,
            events=events,
            point_selection=range(0, total_points_available + 1))
    return render(request, "rewards_index.html", template_data)


@manager_required
def reward_point_redemption_events(request):
    upcoming_events = RewardPointRedemptionEvent.objects.filter(redeem_end_date__gte=datetime.now()).order_by('date')
    past_events = RewardPointRedemptionEvent.objects.filter(redeem_end_date__lt=datetime.now()).order_by('-date')
    template_data = dict(upcoming_events=upcoming_events, past_events=past_events)
    return render(request, "rewards_reward_point_redemption_events.html", template_data)


@manager_required
def reward_point_redemption_event_create(request):
    event = RewardPointRedemptionEvent()
    form = RewardPointRedemptionEventForm(request.POST or None, instance=event)

    if form.is_valid():
        form.save()
        messages.success(request, _("Successfully created event."))
        return redirect('rewards:reward_point_redemption_events')

    return render(request, "rewards_reward_point_redemption_event_form.html", dict(form=form))


@manager_required
def reward_point_redemption_event_edit(request, event_id):
    event = get_object_or_404(RewardPointRedemptionEvent, id=event_id)
    form = RewardPointRedemptionEventForm(request.POST or None, instance=event)

    if form.is_valid():
        event = form.save()

        messages.success(request, _("Successfully updated event."))
        return redirect('rewards:reward_point_redemption_events')

    return render(request, "rewards_reward_point_redemption_event_form.html", dict(event=event, form=form))


@require_POST
@manager_required
def reward_point_redemption_event_delete(request):
    event_id = request.POST.get("event_id")
    event = get_object_or_404(RewardPointRedemptionEvent, id=event_id)

    if not event.can_delete:
        raise SuspiciousOperation("Deleting redemption event not allowed")
    event.delete()
    return HttpResponse()  # 200 OK


@manager_required
def reward_point_redemption_event_export(request, event_id):
    event = get_object_or_404(RewardPointRedemptionEvent, id=event_id)

    filename = _("RewardPoints") + "-%s-%s-%s.xls" % (event.date, event.name, get_language())
    response = FileResponse(filename, content_type="application/vnd.ms-excel")

    RewardsExporter().export(response, event.redemptions_by_user())

    return response


@manager_required
def semester_activation(request, semester_id, active):
    semester = get_object_or_404(Semester, id=semester_id)
    active = active == 'on'

    SemesterActivation.objects.update_or_create(semester=semester, defaults={'is_active': active})

    return semester_view(request=request, semester_id=semester_id)

rewards/views.py
from datetime import datetime

from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import ugettext as _
from django.utils.translation import get_language
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.core.exceptions import SuspiciousOperation

from evap.evaluation.auth import reward_user_required, staff_required
from evap.evaluation.models import Semester

from evap.staff.views import semester_view

from evap.rewards.models import RewardPointGranting, RewardPointRedemption, RewardPointRedemptionEvent, SemesterActivation, NoPointsSelected, NotEnoughPoints
from evap.rewards.tools import save_redemptions, reward_points_of_user
from evap.rewards.forms import RewardPointRedemptionEventForm
from evap.rewards.exporters import ExcelExporter


@reward_user_required
def index(request):
    if request.method == 'POST':
        redemptions = {}
        for key, value in request.POST.items():
            if key.startswith('points-'):
                event_id = int(key.rpartition('-')[2])
                redemptions[event_id] = int(value)

        try:
            save_redemptions(request, redemptions)
            messages.success(request, _("You successfully redeemed your points."))
        except (NoPointsSelected, NotEnoughPoints) as error:
            messages.warning(request, error)

    total_points_available = reward_points_of_user(request.user)
    reward_point_grantings = RewardPointGranting.objects.filter(user_profile=request.user)
    reward_point_redemptions = RewardPointRedemption.objects.filter(user_profile=request.user)
    events = RewardPointRedemptionEvent.objects.filter(redeem_end_date__gte=datetime.now())
    events = sorted(events, key=lambda event: event.date)

    reward_point_actions = []
    for granting in reward_point_grantings:
        reward_point_actions.append((granting.granting_time, _('Reward for') + ' ' + granting.semester.name, granting.value, ''))
    for redemption in reward_point_redemptions:
        reward_point_actions.append((redemption.redemption_time, redemption.event.name, '', redemption.value))

    reward_point_actions.sort(key=lambda action: action[0], reverse=True)

    template_data = dict(
            reward_point_actions=reward_point_actions,
            total_points_available=total_points_available,
            events=events,
            point_selection=[x for x in range(0, total_points_available + 1)])
    return render(request, "rewards_index.html", template_data)


@staff_required
def reward_point_redemption_events(request):
    upcoming_events = RewardPointRedemptionEvent.objects.filter(redeem_end_date__gte=datetime.now()).order_by('date')
    past_events = RewardPointRedemptionEvent.objects.filter(redeem_end_date__lt=datetime.now()).order_by('-date')
    template_data = dict(upcoming_events=upcoming_events, past_events=past_events)
    return render(request, "rewards_reward_point_redemption_events.html", template_data)


@staff_required
def reward_point_redemption_event_create(request):
    event = RewardPointRedemptionEvent()
    form = RewardPointRedemptionEventForm(request.POST or None, instance=event)

    if form.is_valid():
        form.save()
        messages.success(request, _("Successfully created event."))
        return redirect('rewards:reward_point_redemption_events')
    else:
        return render(request, "rewards_reward_point_redemption_event_form.html", dict(form=form))


@staff_required
def reward_point_redemption_event_edit(request, event_id):
    event = get_object_or_404(RewardPointRedemptionEvent, id=event_id)
    form = RewardPointRedemptionEventForm(request.POST or None, instance=event)

    if form.is_valid():
        event = form.save()

        messages.success(request, _("Successfully updated event."))
        return redirect('rewards:reward_point_redemption_events')
    else:
        return render(request, "rewards_reward_point_redemption_event_form.html", dict(event=event, form=form))


@require_POST
@staff_required
def reward_point_redemption_event_delete(request):
    event_id = request.POST.get("event_id")
    event = get_object_or_404(RewardPointRedemptionEvent, id=event_id)

    if not event.can_delete:
        raise SuspiciousOperation("Deleting redemption event not allowed")
    event.delete()
    return HttpResponse()  # 200 OK


@staff_required
def reward_point_redemption_event_export(request, event_id):
    event = get_object_or_404(RewardPointRedemptionEvent, id=event_id)

    filename = _("RewardPoints") + "-%s-%s-%s.xls" % (event.date, event.name, get_language())

    response = HttpResponse(content_type="application/vnd.ms-excel")
    response["Content-Disposition"] = "attachment; filename=\"%s\"" % filename

    ExcelExporter(event.redemptions_by_user()).export(response)

    return response


@staff_required
def semester_activation(request, semester_id, active):
    semester = get_object_or_404(Semester, id=semester_id)
    active = active == 'on'

    SemesterActivation.objects.update_or_create(semester=semester, defaults={'is_active': active})

    return semester_view(request=request, semester_id=semester_id)

rewards/templates/rewards_index.html
{% extends "base.html" %}

{% load morefilters %}

{% block title %}{% trans "Rewards" %} - {{ block.super }}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li><a href="{% url "rewards:index" %}">{% trans "Rewards" %}</a></li>
{% endblock %}

{% block content %}
    {{ block.super }}

    <div class="bs-callout bs-callout-info small">
        {% trans "You will get reward points once you evaluated all your courses in one semester. These points can be redeemed for many events at HPI. You will receive vouchers for food and drinks at the event you selected below. We'll inform you about any upcoming event where you can redeem your reward points." %}
    </div>

    <div class="panel panel-info">
        <div class="panel-heading">
            <span class="panel-title">{% trans "Redeem points" %}</span>
        </div>
        <div class="panel-body">
            <p><b>{% trans "Total points available" %}: {{ total_points_available }}</b></p>
            {% if total_points_available > 0 %}
                {% if events %}
                    <form id="reward-redemption-form" action="#" method="POST" class="form-horizontal multiselect-form">
                        {% csrf_token %}

                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th class="col-sm-2">{% trans "Date" %}</th>
                                    <th class="col-sm-6">{% trans "Event" %}</th>
                                    <th class="col-sm-2">{% trans "Available until" %}</th>
                                    <th class="col-sm-2 text-right">{% trans "Redeem points" %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for event in events %}
                                    <tr>
                                        <td>{{ event.date }}</td>
                                        <td>{{ event.name }}</td>
                                        <td>{{ event.redeem_end_date }}</td>
                                        <td class="text-right">
                                            <select class="form-control pull-right" id="id_points-{{event.id}}" name="points-{{event.id}}" style="width:5em">
                                                {% for p in point_selection %}
                                                    <option value="{{p}}">{{p}}</option>
                                                {% endfor %}
                                            </select>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <input type="submit" class="btn btn-primary pull-right" value="{% trans "Redeem" %}" />
                    </form>
                {% else %}
                    <p><i>{% trans "Currently there are no events available for which you can redeem points. We'll send you a message when this changes." %}</i></p>
                {% endif %}
            {% else %}
                <p><i>{% trans "You don't have any reward points that you could redeem." %}</i></p>
            {% endif %}
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="panel-title">{% trans "Reward points history" %}</span>
        </div>
        <div class="panel-body">
            {% if reward_point_actions %}
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th class="col-sm-3">{% trans "Date" %}</th>
                            <th class="col-sm-7">{% trans "Action" %}</th>
                            <th class="col-sm-1 text-right">{% trans "Granted points" %}</th>
                            <th class="col-sm-1 text-right">{% trans "Redeemed points" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for action_time, event_name, granting_value, redemption_value in reward_point_actions %}
                            <tr>
                                <td>{{ action_time }}</td>
                                <td>{{ event_name }}</td>
                                <td class="text-right">{{ granting_value }}</td>
                                <td class="text-right">{{ redemption_value }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p><i>{% trans "No reward points earned yet." %}</i></p>
            {% endif %}
        </div>
    </div>
{% endblock %}


{% block on_document_ready %}
    $('.dropdown-toggle').dropdown()
{% endblock %}

rewards/templates/rewards_reward_point_redemption_event_form.html
{% extends "staff_base.html" %}

{% load bootstrap3 %}

{% block breadcrumb %}
    {{ block.super }}
    <li><a href="{% url "rewards:reward_point_redemption_events" %}">{% trans "Reward Point Redemption Events" %}</a></li>
    <li>{% trans "Edit event" %}</li>
{% endblock %}

{% block content %}
    {{ block.super }}
    <form id="reward-point-redemption-event-form" method="POST" class="form-horizontal">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <div class="form-group well">
            <div class="col-sm-offset-2 col-sm-6">
                <input type="submit" value="{% trans "Save event" %}" class="btn btn-primary"/>
            </div>
        </div>
    </form>
{% endblock %}

rewards/templates/rewards_reward_point_redemption_events.html
{% extends "staff_base.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>{% trans "Reward Point Redemption Events" %}</li>
{% endblock %}

{% block content %}
    {{ block.super }}

    <p>
        <a href="{% url "rewards:reward_point_redemption_event_create" %}" class="btn btn-success btn-sm">{% trans "Create new event" %}</a>
    </p>
    <div class="panel panel-info">
        <div class="panel-heading">
            <span class="panel-title">{% trans "Upcoming events" %}</span>
        </div>
        <div class="panel-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th class="col-sm-2">{% trans "Event date" %}</th>
                        <th class="col-sm-2">{% trans "Redemption end date" %}</th>
                        <th class="col-sm-3">{% trans "Event name" %}</th>
                        <th class="col-sm-1">{% trans "Redemptions" %}</th>
                        <th class="col-sm-4">{% trans "Actions" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for event in upcoming_events %}
                        <tr id="event-row-{{ event.id }}">
                            <td>{{ event.date }}</td>
                            <td>{{ event.redeem_end_date }}</td>
                            <td>{{ event.name }}</td>
                            <td><span class="glyphicon glyphicon-user"></span> {{ event.redemptions_by_user|length }}
                            <td>
                                <a href="{% url "rewards:reward_point_redemption_event_export" event.id %}" class="btn btn-sm btn-default">{% trans "Export Redemptions" %}</a>
                                <a href="{% url "rewards:reward_point_redemption_event_edit" event.id %}" class="btn btn-sm btn-default">{% trans "Edit" %}</a>
                                {% if event.can_delete %}
                                    <a onclick="show_delete_event_modal({{ event.id }}, '{{ event.name|escapejs }}');" class="btn btn-danger btn-sm">{% trans "Delete" %}</a>
                                {% else %}
                                    <div data-toggle="tooltip" data-placement="left" class="disabled-tooltip" title="{% trans "This event cannot be deleted because some users already redeemed points for it." %}"><a class="btn btn-sm btn-danger disabled">{% trans "Delete" %}</a></div>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="panel-title">{% trans "Past events" %}</span>
        </div>
        <div class="panel-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th class="col-sm-2">{% trans "Event date" %}</th>
                        <th class="col-sm-2">{% trans "Redemption end date" %}</th>
                        <th class="col-sm-3">{% trans "Event name" %}</th>
                        <th class="col-sm-1">{% trans "Redemptions" %}</th>
                        <th class="col-sm-4">{% trans "Actions" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for event in past_events %}
                        <tr id="event-row-{{ event.id }}">
                            <td>{{ event.date }}</td>
                            <td>{{ event.redeem_end_date }}</td>
                            <td>{{ event.name }}</td>
                            <td><span class="glyphicon glyphicon-user"></span> {{ event.reward_point_redemptions.all|length }}
                            <td>
                                <a href="{% url "rewards:reward_point_redemption_event_export" event.id %}" class="btn btn-sm btn-default">{% trans "Export Redemptions" %}</a>
                                <a href="{% url "rewards:reward_point_redemption_event_edit" event.id %}" class="btn btn-sm btn-default">{% trans "Edit" %}</a>
                                {% if event.can_delete %}
                                    <a onclick="show_delete_event_modal({{ event.id }}, '{{ event.name|escapejs }}');" class="btn btn-danger btn-sm">{% trans "Delete" %}</a>
                                {% else %}
                                    <div data-toggle="tooltip" data-placement="left" class="disabled-tooltip" title="{% trans "This event cannot be deleted because some users already redeemed points for it." %}"><a class="btn btn-sm btn-danger disabled">{% trans "Delete" %}</a></div>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block modals %}
    {{ block.super }}
    {% trans "Delete event" as title %}
    {% trans 'Do you really want to delete the event <strong id="data-label"></strong>?' as question %}
    {% trans "Delete event" as action_text %}
    {% include "confirmation_modal.html" with modal_id="delete_event_modal" title=title question=question action_text=action_text btn_type="danger" %}
    <script type="text/javascript">
        function delete_event_modal_action(data_id) {
            $.ajax({
                type: "POST",
                url: "{% url "rewards:reward_point_redemption_event_delete" %}",
                data: {"event_id": data_id},
                success: function(){ $('#event-row-'+data_id).hide('slow', function(){ $('#event-row-'+data_id).remove(); }); },
                error: function(){ $('#event-row-'+data_id).effect("highlight", {color:"#eb595a"}, 2000); }
            });
        };
    </script>
{% endblock %}