contributor/urls.py
from django.conf.urls import url

from evap.contributor.views import index, settings_edit, course_view, course_edit, course_preview


app_name = "contributor"

urlpatterns = [
    url(r"^$", index, name="index"),
    url(r"^settings$", settings_edit, name="settings_edit"),
    url(r"^course/(\d+)$", course_view, name="course_view"),
    url(r"^course/(\d+)/edit$", course_edit, name="course_edit"),
    url(r"^course/(\d+)/preview$", course_preview, name="course_preview"),
]

evap/contributor/urls.py
from django.urls import path

from evap.contributor import views


app_name = "contributor"

urlpatterns = [
    path("", views.index, name="index"),
    path("settings", views.settings_edit, name="settings_edit"),
    path("export", views.export, name="export"),
    path("evaluation/<int:evaluation_id>", views.evaluation_view, name="evaluation_view"),
    path("evaluation/<int:evaluation_id>/edit", views.evaluation_edit, name="evaluation_edit"),
    path("evaluation/<int:evaluation_id>/preview", views.evaluation_preview, name="evaluation_preview"),
    path("evaluation/<int:evaluation_id>/direct_delegation", views.evaluation_direct_delegation, name="evaluation_direct_delegation")
]

evap/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import include, path
import django.contrib.auth.views


urlpatterns = [
    path("", include('evap.evaluation.urls')),
    path("staff/", include('evap.staff.urls')),
    path("results/", include('evap.results.urls')),
    path("student/", include('evap.student.urls')),
    path("contributor/", include('evap.contributor.urls')),
    path("rewards/", include('evap.rewards.urls')),
    path("grades/", include('evap.grades.urls')),

    path("logout", django.contrib.auth.views.LogoutView.as_view(next_page="/"), name="django-auth-logout"),
    url(r'^oidc/', include('mozilla_django_oidc.urls')),
]

if settings.DEBUG and settings.ENABLE_DEBUG_TOOLBAR:
    # pylint does not correctly evaluate this if, so it will raise an import-error on
    # travis and a useless-suppression on a vagrant setup. Ignore both cases.
    import debug_toolbar  # pylint: disable=import-error, useless-suppression
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

results/urls.py
from django.conf.urls import url

from evap.results.views import index, semester_detail, course_detail


app_name = "results"

urlpatterns = [
    url(r"^$", index, name="index"),
    url(r"semester/(\d+)$", semester_detail, name="semester_detail"),
    url(r"semester/(\d+)/course/(\d+)$", course_detail, name="course_detail"),
]

urls.py
from django.conf import settings
from django.conf.urls import include, url
import django.views.static
import django.contrib.auth.views

from django.contrib import admin
admin.autodiscover()


urlpatterns = [
    url(r"^", include('evap.evaluation.urls')),
    url(r"^staff/", include('evap.staff.urls')),
    url(r"^results/", include('evap.results.urls')),
    url(r"^student/", include('evap.student.urls')),
    url(r"^contributor/", include('evap.contributor.urls')),
    url(r"^rewards/", include('evap.rewards.urls')),
    url(r"^grades/", include('evap.grades.urls')),

    url(r"^logout$", django.contrib.auth.views.logout, {'next_page': "/"}, name="django-auth-logout"),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r"^admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT})]

if settings.DEBUG and settings.ENABLE_DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]

contributor/forms.py
import logging
import datetime

from django import forms
from django.forms.widgets import CheckboxSelectMultiple
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
from django.db.models import Q

from evap.evaluation.models import Course, UserProfile, Questionnaire, Semester
from evap.staff.forms import ContributionForm


logger = logging.getLogger(__name__)


class CourseForm(forms.ModelForm):
    general_questions = forms.ModelMultipleChoiceField(queryset=None, widget=CheckboxSelectMultiple, label=_("Questions about the course"))
    semester = forms.ModelChoiceField(Semester.objects.all(), disabled=True, required=False, widget=forms.HiddenInput())

    class Meta:
        model = Course
        fields = ('name_de', 'name_en', 'vote_start_date', 'vote_end_date', 'type', 'degrees', 'general_questions', 'semester')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['general_questions'].queryset = Questionnaire.objects.filter(is_for_contributors=False).filter(
            (Q(staff_only=False) & Q(obsolete=False)) | Q(contributions__course=self.instance)).distinct()

        self.fields['vote_start_date'].localize = True
        self.fields['vote_end_date'].localize = True
        self.fields['degrees'].disabled = True
        self.fields['degrees'].help_text = ""

        if self.instance.general_contribution:
            self.fields['general_questions'].initial = [q.pk for q in self.instance.general_contribution.questionnaires.all()]

    def clean(self):
        super().clean()

        vote_start_date = self.cleaned_data.get('vote_start_date')
        vote_end_date = self.cleaned_data.get('vote_end_date')
        if vote_start_date and vote_end_date:
            if vote_start_date >= vote_end_date:
                raise ValidationError(_("The first day of evaluation must be before the last one."))

    def clean_vote_start_date(self):
        vote_start_date = self.cleaned_data.get('vote_start_date')
        if vote_start_date and vote_start_date < datetime.datetime.now():
            raise forms.ValidationError(_("The first day of evaluation must be in the future."))
        return vote_start_date

    def clean_vote_end_date(self):
        vote_end_date = self.cleaned_data.get('vote_end_date')
        if vote_end_date and vote_end_date < datetime.datetime.now():
            raise forms.ValidationError(_("The last day of evaluation must be in the future."))
        return vote_end_date

    def save(self, *args, **kw):
        user = kw.pop("user")
        self.instance.last_modified_user = user
        super().save(*args, **kw)
        self.instance.general_contribution.questionnaires = self.cleaned_data.get('general_questions')
        logger.info('Course "{}" (id {}) was edited by contributor {}.'.format(self.instance, self.instance.id, user.username))


class EditorContributionForm(ContributionForm):
    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        if self.instance.responsible:
            self.fields['responsibility'].disabled = True
            self.fields['contributor'].disabled = True
            self.fields['comment_visibility'].disabled = True

        self.fields['questionnaires'].queryset = Questionnaire.objects.filter(is_for_contributors=True).filter(
            (Q(staff_only=False) & Q(obsolete=False)) | Q(contributions__course=self.course)).distinct()


class DelegatesForm(forms.ModelForm):
    delegate_of = forms.ModelMultipleChoiceField(None, required=False, disabled=True)
    cc_user_of = forms.ModelMultipleChoiceField(None, required=False, disabled=True)

    class Meta:
        model = UserProfile
        fields = ('delegates', 'cc_users',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['cc_users'].disabled = True

        represented_users = self.instance.represented_users.all()
        self.fields['delegate_of'].queryset = represented_users
        self.fields['delegate_of'].initial = represented_users
        # work around https://code.djangoproject.com/ticket/25980
        self.fields['delegate_of'].initial = list(represented_users.values_list('pk', flat=True))

        ccing_users = self.instance.ccing_users.all()
        self.fields['cc_user_of'].queryset = ccing_users
        self.fields['cc_user_of'].initial = ccing_users
        # work around https://code.djangoproject.com/ticket/25980
        self.fields['cc_user_of'].initial = list(ccing_users.values_list('pk', flat=True))

    def save(self, *args, **kw):
        super().save(*args, **kw)
        logger.info('User "{}" edited the settings.'.format(self.instance.username))

contributor/views.py
from django.contrib import messages
from django.core.exceptions import PermissionDenied, SuspiciousOperation
from django.forms.models import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import ugettext as _

from evap.evaluation.models import Contribution, Course, Semester
from evap.evaluation.auth import editor_required, editor_or_delegate_required, contributor_or_delegate_required
from evap.evaluation.tools import STATES_ORDERED, sort_formset
from evap.contributor.forms import CourseForm, DelegatesForm
from evap.staff.forms import ContributionFormSet
from evap.contributor.forms import EditorContributionForm
from evap.student.views import vote_preview


@contributor_or_delegate_required
def index(request):
    user = request.user

    contributor_visible_states = ['prepared', 'editor_approved', 'approved', 'in_evaluation', 'evaluated', 'reviewed', 'published']
    own_courses = Course.objects.filter(contributions__contributor=user, state__in=contributor_visible_states)

    represented_users = user.represented_users.all()
    delegated_courses = Course.objects.exclude(id__in=own_courses).filter(contributions__can_edit=True, contributions__contributor__in=represented_users, state__in=contributor_visible_states)

    all_courses = list(own_courses) + list(delegated_courses)
    all_courses.sort(key=lambda course: list(STATES_ORDERED.keys()).index(course.state))

    semesters = Semester.objects.all()
    semester_list = [dict(semester_name=semester.name, id=semester.id, courses=[course for course in all_courses if course.semester_id == semester.id]) for semester in semesters]

    template_data = dict(semester_list=semester_list, delegated_courses=delegated_courses)
    return render(request, "contributor_index.html", template_data)


@editor_required
def settings_edit(request):
    user = request.user
    form = DelegatesForm(request.POST or None, request.FILES or None, instance=user)

    if form.is_valid():
        form.save()

        messages.success(request, _("Successfully updated your settings."))
        return redirect('contributor:index')
    else:
        return render(request, "contributor_settings.html", dict(form=form, user=user))


@editor_or_delegate_required
def course_view(request, course_id):
    user = request.user
    course = get_object_or_404(Course, id=course_id)

    # check rights
    if not (course.is_user_editor_or_delegate(user) and course.state in ['prepared', 'editor_approved', 'approved', 'in_evaluation', 'evaluated', 'reviewed']):
        raise PermissionDenied

    InlineContributionFormset = inlineformset_factory(Course, Contribution, formset=ContributionFormSet, form=EditorContributionForm, extra=0)

    form = CourseForm(request.POST or None, instance=course)
    formset = InlineContributionFormset(request.POST or None, instance=course)

    # make everything read-only
    for cform in formset.forms + [form]:
        for field in cform.fields.values():
            field.disabled = True

    template_data = dict(form=form, formset=formset, course=course, editable=False, responsible=course.responsible_contributor.username)
    return render(request, "contributor_course_form.html", template_data)


@editor_or_delegate_required
def course_edit(request, course_id):
    user = request.user
    course = get_object_or_404(Course, id=course_id)

    # check rights
    if not (course.is_user_editor_or_delegate(user) and course.state == 'prepared'):
        raise PermissionDenied

    InlineContributionFormset = inlineformset_factory(Course, Contribution, formset=ContributionFormSet, form=EditorContributionForm, extra=1)

    course_form = CourseForm(request.POST or None, instance=course)
    formset = InlineContributionFormset(request.POST or None, instance=course, form_kwargs={'course': course})

    operation = request.POST.get('operation')

    if course_form.is_valid() and formset.is_valid():
        if operation not in ('save', 'approve'):
            raise SuspiciousOperation("Invalid POST operation")

        course_form.save(user=user)
        formset.save()

        if operation == 'approve':
            # approve course
            course.editor_approve()
            course.save()
            messages.success(request, _("Successfully updated and approved course."))
        else:
            messages.success(request, _("Successfully updated course."))

        return redirect('contributor:index')
    else:
        sort_formset(request, formset)
        template_data = dict(form=course_form, formset=formset, course=course, editable=True, responsible=course.responsible_contributor.username)
        return render(request, "contributor_course_form.html", template_data)


@contributor_or_delegate_required
def course_preview(request, course_id):
    user = request.user
    course = get_object_or_404(Course, id=course_id)

    # check rights
    if not (course.is_user_contributor_or_delegate(user) and course.state in ['prepared', 'editor_approved', 'approved', 'in_evaluation', 'evaluated', 'reviewed']):
        raise PermissionDenied

    return vote_preview(request, course)

contributor/templates/contributor_base.html
{% extends "base.html" %}

{% block title %}{% trans "Your EvaP" %} - {{ block.super }}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    {% if form %}
        <li><a href="{% url "contributor:index" %}">{% trans "Contributor" %}</a></li>
    {% else %}
        <li>{% trans "Contributor" %}</li>
    {% endif %}
{% endblock %}

contributor/templates/contributor_course_form.html
{% extends "contributor_base.html" %}

{% load bootstrap3 %}
{% load morefilters %}

{% block breadcrumb %}
    {{ block.super }}
    <li>{{ course.name }}</li>
{% endblock %}

{% block content %}
    {{ block.super }}
    <form method="POST" class="form-horizontal multiselect-form select2form" id="course-form">
        {% csrf_token %}

        {% include 'course_form_general_questions.html' with course=course course_form=form %}

        {% include "contribution_formset.html" with formset=formset staff=False editable=True%}

        <fieldset>
            <legend>{% trans "Students" %}</legend>
            <p>{% trans "These students should be participating in your course. If this data is not correct, e.g. when students are missing from the list, please contact the student representatives." %}</p>
            <ul>
                {% for p in course.participants.all|dictsort:"last_name" %}
                    <li>{{ p.full_name }}</li>
                {% endfor %}
            </ul>
        </fieldset>
        <div class="form-group well">
            <div class="col-sm-offset-2 col-sm-6">
                {% if editable %}
                    <button name="operation" value="save" type="submit" onclick="preventAccidentalClosing = false;" class="btn btn-primary">{% trans "Save"%}</button>
                    {# webtest does not allow submission with value "approve" if no such button exists #}
                    <button style="display: none" name="operation" value="approve" type="submit" />
                    <button onclick="preventAccidentalClosing = false; show_approve_course_modal(0, '');" type="button" class="btn btn-success">{% trans "Save and approve"%}</button>
                {% endif %}
                <a href="{% url "contributor:index" %}" class="btn btn-default">{% if edit == False %} {% trans "Back" %} {% else %} {% trans "Cancel" %} {% endif %}</a>
            </div>
        </div>
    </form>
{% endblock %}

{% block modals %}
    {{ block.super }}
    {% trans "Approve course" as title %}
    {% trans "Do you want to approve this course? This will allow the student representatives to proceed with the preparation, but you won't be able to make any further changes." as question %}
    {% trans "Approve course" as action_text %}
    {% include "confirmation_modal.html" with modal_id="approve_course_modal" title=title question=question action_text=action_text btn_type="primary" %}
    <script type="text/javascript">
        function approve_course_modal_action(data_id) {
            $('#course-form').append('<input type="hidden" name="operation" value="approve">');
            $('#course-form').submit();
        };
    </script>
{% endblock %}

{% block additional_javascript %}
    {% include "evap_course_edit_js.html" %}
    {% if editable %}
        <script type="text/javascript"> preventAccidentalClosing = true; </script>
    {% endif %}
{% endblock %}

contributor/templates/contributor_index.html
{% extends "contributor_base.html" %}

{% load morefilters %}

{% block content %}
    {{ block.super }}

    <div class="bs-callout bs-callout-info small">
        <b>{% trans "Delegates" %}</b><br />
        {% blocktrans %}Lecturers can assign delegates to help them with the preparation of the evaluation.{% endblocktrans %}
        {% if user.is_editor %}
            {% blocktrans %}You can assign your own delegates on your settings page.{% endblocktrans %} <a href="{% url "contributor:settings_edit" %}" class="btn btn-xs btn-default">{% trans "Edit settings" %}</a><br />
        {% endif %}
        {% if delegated_courses %}
            {% blocktrans %}Courses from lecturers who set you as a delegate are marked with a label below.{% endblocktrans %}<br />
        {% endif %}
        <em>{% trans "More details:" %} <a href="/faq#15">{% trans "FAQ/Delegates" %}</a></em><br />
        <br />
        <b>{% trans "States of the courses" %}</b><br />
        {% blocktrans %}You can only edit courses which are in the state "prepared". After you approved a course it will automatically change to the state "lecturer approved" and your preparation is finished.{% endblocktrans %}<br />
        <em>{% trans "More details:" %} <a href="/faq#18">{% trans "FAQ/States" %}</a></em><br />
        <br />
        <b>{% trans "Evaluation Results" %}</b><br />
        {% blocktrans %}The student's comments will be shown to the people who were evaluated and to the person responsible for the course – after the grades of all the course's exams have been published. In addition all average grades will then be published for all users of the platform if at least 20 percent of the course's students participated in the evaluation.{% endblocktrans %}<br />
        <em>{% trans "More details:" %} <a href="/faq#3-s">{% trans "FAQ/Results" %}</a></em>
    </div>

    {% for semester in semester_list %}
        {% if semester.courses %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="panel-title">{{ semester.semester_name }}</span>
            </div>
            <div class="panel-body">
                <table class="table table-striped vertically-aligned">
                    <thead>
                    <tr>
                        <th class="col-sm-4">{% trans "Name" %}</th>
                        <th class="col-sm-2">{% trans "State" %}</th>
                        <th class="col-sm-2">{% trans "Evaluation Period" %}</th>
                        <th class="col-sm-1">{% trans "Participants" %}</th>
                        <th class="col-sm-3"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for course in semester.courses %}
                        <tr>
                            <td>
                                <div>
                                    {{ course.name }}
                                </div>
                                <span class="label label-default">{{ course.type }}</span>
                                {% if course in delegated_courses %}<span class="label label-info" data-toggle="tooltip" data-placement="right" title="{% trans "You are seeing this course because you are a delegate of a lecturer who can edit the course." %}">{% trans "Delegate" %}</span>{% endif %}
                            </td>
                            <td>
                                <span data-toggle="tooltip" data-placement="left" title="{{ course.state|statedescription }}">{{ course.state|statename }}</span>
                            </td>
                            <td>
                                {{ course.vote_start_date|date:'SHORT_DATETIME_FORMAT' }}{% if not course.is_single_result %} &ndash;</br> {{ course.vote_end_date|date:'SHORT_DATETIME_FORMAT' }}{% endif %}
                            </td>
                            <td>
                                {% if course.is_single_result %}&mdash;{% else %}{{ course.num_participants }}{% endif %}
                            </td>
                            <td class="text-right">
                                {% if course|is_user_editor_or_delegate:user %}
                                    {% if course.state == 'prepared' %}
                                        <a href="{% url "contributor:course_edit" course.id %}" class="btn btn-sm btn-primary">{% trans "Edit" %}</a>
                                        <a href="{% url "contributor:course_preview" course.id %}" class="btn btn-sm btn-default">{% trans "Preview" %}</a>
                                    {% elif course.state == 'editor_approved' or course.state == 'approved' %}
                                        <a href="{% url "contributor:course_view" course.id %}" class="btn btn-sm btn-default">{% trans "View" %}</a>
                                        <a href="{% url "contributor:course_preview" course.id %}" class="btn btn-sm btn-default">{% trans "Preview" %}</a>
                                    {% endif %}
                                {% endif %}
                                {% if course.state != 'published' %}
                                    <div data-toggle="tooltip" data-placement="left" class="disabled-tooltip" title="{% trans "The results are not yet available. You will receive an email once they are published." %}"><a class="btn btn-sm btn-default disabled">{% trans "Results" %}</a></div>
                                {% else %}
                                    <a href="{% url "results:course_detail" semester.id course.id %}" class="btn btn-sm btn-default">{% trans "Results" %}</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endif %}
    {% endfor %}

{% endblock %}

contributor/templates/contributor_settings.html
{% extends "contributor_base.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>{% trans "Settings" %}</li>
{% endblock %}

{% block content %}
    {{ block.super }}
    <h2>{% trans "Settings" %}</h2>

    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="panel-title">{% trans "Personal information" %}
                <span data-toggle="tooltip" data-placement="left" class="glyphicon glyphicon-info-sign pull-right"
                title="{% trans "To change any of these settings, please contact the student representatives." %}">
                </span>
            </span>
        </div>
        <div class="panel-body">
            <table class="table table-striped vertically-aligned">
                <tr>
                    <td class="col-sm-2"><strong>{% trans "Username" %}</strong></td>
                    <td class="col-sm-10">{{ user.username }}</td>
                </tr>
                <tr>
                    <td><strong>{% trans "Title" %}</strong></td>
                    <td>{{ user.title }}</td>
                </tr>
                <tr>
                    <td><strong>{% trans "First name" %}</strong></td>
                    <td>{{ user.first_name }}</td>
                </tr>
                <tr>
                    <td><strong>{% trans "Last name" %}</strong></td>
                    <td>{{ user.last_name }}</td>
                </tr>
                <tr>
                    <td><strong>{% trans "Email" %}</strong></td>
                    <td>{{ user.email }}</td>
                </tr>
            </table>
        </div>
    </div>

    <form method="POST" class="form-horizontal multiselect-form settings-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="panel-title">{% trans "Delegates and CC users" %}
                    <span data-toggle="tooltip" data-placement="left" class="glyphicon glyphicon-info-sign pull-right"
                    title="{% blocktrans %}You can only change your own delegates. To become a delegate of another person this person has to add you.
                    Please contact the student representatives to change the CC settings.{% endblocktrans %}">
                    </span>
                </span>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <span class="panel-title">{% trans "Own delegates" %}</span>
                            </div>
                            <div class="panel-body">
                                {{ form.delegates.errors }}
                                {{ form.delegates }}
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <span class="panel-title">{% trans "You are a delegate of" %}</span>
                            </div>
                            <div class="panel-body">
                                {{ form.delegate_of.errors }}
                                {{ form.delegate_of }}
                            </div>
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-sm-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <span class="panel-title">{% trans "Emails sent to you will be CC'ed to" %}</span>
                            </div>
                            <div class="panel-body">
                                {{ form.cc_users.errors }}
                                {{ form.cc_users }}
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <span class="panel-title">{% trans "Emails sent to these users will be CC'ed to you" %}</span>
                            </div>
                            <div class="panel-body">
                                {{ form.cc_user_of.errors }}
                                {{ form.cc_user_of }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {{ form.cc_users.as_hidden }} {# disabled elements are not sent in the post and select2 doesn't work with readonly #}

        <div class="well submit-area text-center">
            <input type="submit" value="{% trans "Save changes" %}" class="btn btn-primary"/>
        </div>
    </form>
{% endblock %}