evap/staff/urls.py
from django.urls import path
from django.views.generic import RedirectView

from evap.staff import views


app_name = "staff"

urlpatterns = [
    path("", views.index, name="index"),

    path("semester/", RedirectView.as_view(url='/staff/', permanent=True)),
    path("semester/create", views.semester_create, name="semester_create"),
    path("semester/<int:semester_id>", views.semester_view, name="semester_view"),
    path("semester/<int:semester_id>/edit", views.semester_edit, name="semester_edit"),
    path("semester/<int:semester_id>/import", views.semester_import, name="semester_import"),
    path("semester/<int:semester_id>/export", views.semester_export, name="semester_export"),
    path("semester/<int:semester_id>/raw_export", views.semester_raw_export, name="semester_raw_export"),
    path("semester/<int:semester_id>/participation_export", views.semester_participation_export, name="semester_participation_export"),
    path("semester/<int:semester_id>/assign", views.semester_questionnaire_assign, name="semester_questionnaire_assign"),
    path("semester/<int:semester_id>/preparation_reminder", views.semester_preparation_reminder, name="semester_preparation_reminder"),
    path("semester/<int:semester_id>/grade_reminder", views.semester_grade_reminder, name="semester_grade_reminder"),
    path("semester/<int:semester_id>/course/create", views.course_create, name="course_create"),
    path("semester/<int:semester_id>/course/<int:course_id>/edit", views.course_edit, name="course_edit"),
    path("semester/<int:semester_id>/evaluation/create", views.evaluation_create, name="evaluation_create"),
    path("semester/<int:semester_id>/evaluation/create/<int:course_id>", views.evaluation_create, name="evaluation_create"),
    path("semester/<int:semester_id>/evaluation/<int:evaluation_id>/edit", views.evaluation_edit, name="evaluation_edit"),
    path("semester/<int:semester_id>/evaluation/<int:evaluation_id>/copy", views.evaluation_copy, name="evaluation_copy"),
    path("semester/<int:semester_id>/evaluation/<int:evaluation_id>/email", views.evaluation_email, name="evaluation_email"),
    path("semester/<int:semester_id>/evaluation/<int:evaluation_id>/preview", views.evaluation_preview, name="evaluation_preview"),
    path("semester/<int:semester_id>/evaluation/<int:evaluation_id>/person_management", views.evaluation_person_management, name="evaluation_person_management"),
    path("semester/<int:semester_id>/evaluation/<int:evaluation_id>/login_key_export", views.evaluation_login_key_export, name="evaluation_login_key_export"),
    path("semester/<int:semester_id>/evaluation/<int:evaluation_id>/textanswers", views.evaluation_textanswers, name="evaluation_textanswers"),
    path("semester/<int:semester_id>/evaluation/<int:evaluation_id>/textanswer/<uuid:textanswer_id>/edit", views.evaluation_textanswer_edit, name="evaluation_textanswer_edit"),
    path("semester/<int:semester_id>/evaluationoperation", views.semester_evaluation_operation, name="semester_evaluation_operation"),
    path("semester/<int:semester_id>/singleresult/create", views.single_result_create, name="single_result_create"),
    path("semester/<int:semester_id>/singleresult/create/<int:course_id>", views.single_result_create, name="single_result_create"),
    path("semester/<int:semester_id>/responsible/<int:responsible_id>/send_reminder", views.send_reminder, name="send_reminder"),

    path("semester/delete", views.semester_delete, name="semester_delete"),
    path("semester/archive_participations", views.semester_archive_participations, name="semester_archive_participations"),
    path("semester/delete_grade_documents", views.semester_delete_grade_documents, name="semester_delete_grade_documents"),
    path("semester/archive_results", views.semester_archive_results, name="semester_archive_results"),
    path("semester/course_delete", views.course_delete, name="course_delete"),
    path("semester/evaluation_delete", views.evaluation_delete, name="evaluation_delete"),
    path("semester/make_active", views.semester_make_active, name="semester_make_active"),

    path("textanswers/update_publish", views.evaluation_textanswers_update_publish, name="evaluation_textanswers_update_publish"),

    path("questionnaire/", views.questionnaire_index, name="questionnaire_index"),
    path("questionnaire/create", views.questionnaire_create, name="questionnaire_create"),
    path("questionnaire/<int:questionnaire_id>", views.questionnaire_view, name="questionnaire_view"),
    path("questionnaire/<int:questionnaire_id>/edit", views.questionnaire_edit, name="questionnaire_edit"),
    path("questionnaire/<int:questionnaire_id>/new_version", views.questionnaire_new_version, name="questionnaire_new_version"),
    path("questionnaire/<int:questionnaire_id>/copy", views.questionnaire_copy, name="questionnaire_copy"),
    path("questionnaire/delete", views.questionnaire_delete, name="questionnaire_delete"),
    path("questionnaire/update_indices", views.questionnaire_update_indices, name="questionnaire_update_indices"),
    path("questionnaire/questionnaire_visibility", views.questionnaire_visibility, name="questionnaire_visibility"),
    path("questionnaire/questionnaire_set_locked", views.questionnaire_set_locked, name="questionnaire_set_locked"),

    path("degrees/", views.degree_index, name="degree_index"),

    path("course_types/", views.course_type_index, name="course_type_index"),
    path("course_types/merge", views.course_type_merge_selection, name="course_type_merge_selection"),
    path("course_types/<int:main_type_id>/merge/<int:other_type_id>", views.course_type_merge, name="course_type_merge"),

    path("user/", views.user_index, name="user_index"),
    path("user/create", views.user_create, name="user_create"),
    path("user/import", views.user_import, name="user_import"),
    path("user/<int:user_id>/edit", views.user_edit, name="user_edit"),

    path("user/delete", views.user_delete, name="user_delete"),
    path("user/bulk_update", views.user_bulk_update, name="user_bulk_update"),
    path("user/merge", views.user_merge_selection, name="user_merge_selection"),
    path("user/<int:main_user_id>/merge/<int:other_user_id>", views.user_merge, name="user_merge"),

    path("template/", RedirectView.as_view(url='/staff/', permanent=True)),
    path("template/<int:template_id>", views.template_edit, name="template_edit"),

    path("text_answer_warnings/", views.text_answer_warnings_index, name="text_answer_warnings"),

    path("faq/", views.faq_index, name="faq_index"),
    path("faq/<int:section_id>", views.faq_section, name="faq_section"),

    path("download_sample_xls/<str:filename>", views.download_sample_xls, name="download_sample_xls"),

    path("development/components", views.development_components, name="development_components"),

    path("export_contributor_results/<int:contributor_id>", views.export_contributor_results_view, name="export_contributor_results"),

    path("enter_staff_mode", views.enter_staff_mode, name="enter_staff_mode"),
    path("exit_staff_mode", views.exit_staff_mode, name="exit_staff_mode"),
]

evap/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import include, path
import django.contrib.auth.views


urlpatterns = [
    path("", include('evap.evaluation.urls')),
    path("staff/", include('evap.staff.urls')),
    path("results/", include('evap.results.urls')),
    path("student/", include('evap.student.urls')),
    path("contributor/", include('evap.contributor.urls')),
    path("rewards/", include('evap.rewards.urls')),
    path("grades/", include('evap.grades.urls')),

    path("logout", django.contrib.auth.views.LogoutView.as_view(next_page="/"), name="django-auth-logout"),
    url(r'^oidc/', include('mozilla_django_oidc.urls')),
]

if settings.DEBUG and settings.ENABLE_DEBUG_TOOLBAR:
    # pylint does not correctly evaluate this if, so it will raise an import-error on
    # travis and a useless-suppression on a vagrant setup. Ignore both cases.
    import debug_toolbar  # pylint: disable=import-error, useless-suppression
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

staff/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from evap.staff.views import *


app_name = "staff"

urlpatterns = [
    url(r"^$", index, name="index"),

    url(r"^semester/$", RedirectView.as_view(url='/staff/', permanent=True)),
    url(r"^semester/create$", semester_create, name="semester_create"),
    url(r"^semester/(\d+)$", semester_view, name="semester_view"),
    url(r"^semester/(\d+)/edit$", semester_edit, name="semester_edit"),
    url(r"^semester/(\d+)/import$", semester_import, name="semester_import"),
    url(r"^semester/(\d+)/export$", semester_export, name="semester_export"),
    url(r"^semester/(\d+)/raw_export$", semester_raw_export, name="semester_raw_export"),
    url(r"^semester/(\d+)/participation_export$", semester_participation_export, name="semester_participation_export"),
    url(r"^semester/(\d+)/assign$", semester_questionnaire_assign, name="semester_questionnaire_assign"),
    url(r"^semester/(\d+)/todo", semester_todo, name="semester_todo"),
    url(r"^semester/(\d+)/lottery$", semester_lottery, name="semester_lottery"),
    url(r"^semester/(\d+)/course/create$", course_create, name="course_create"),
    url(r"^semester/(\d+)/course/(\d+)/edit$", course_edit, name="course_edit"),
    url(r"^semester/(\d+)/course/(\d+)/email$", course_email, name="course_email"),
    url(r"^semester/(\d+)/course/(\d+)/preview$", course_preview, name="course_preview"),
    url(r"^semester/(\d+)/course/(\d+)/participant_import", course_participant_import, name="course_participant_import"),
    url(r"^semester/(\d+)/course/(\d+)/comments$", course_comments, name="course_comments"),
    url(r"^semester/(\d+)/course/(\d+)/comment/(\d+)/edit$", course_comment_edit, name="course_comment_edit"),
    url(r"^semester/(\d+)/courseoperation$", semester_course_operation, name="semester_course_operation"),
    url(r"^semester/(\d+)/singleresult/create$", single_result_create, name="single_result_create"),

    url(r"^semester/delete$", semester_delete, name="semester_delete"),
    url(r"^semester/archive$", semester_archive, name="semester_archive"),
    url(r"^semester/course_delete$", course_delete, name="course_delete"),

    url(r"^comments/update_publish$", course_comments_update_publish, name="course_comments_update_publish"),

    url(r"^questionnaire/$", questionnaire_index, name="questionnaire_index"),
    url(r"^questionnaire/create$", questionnaire_create, name="questionnaire_create"),
    url(r"^questionnaire/(\d+)$", questionnaire_view, name="questionnaire_view"),
    url(r"^questionnaire/(\d+)/edit$", questionnaire_edit, name="questionnaire_edit"),
    url(r"^questionnaire/(\d+)/new_version", questionnaire_new_version, name="questionnaire_new_version"),
    url(r"^questionnaire/(\d+)/copy$", questionnaire_copy, name="questionnaire_copy"),
    url(r"^questionnaire/delete$", questionnaire_delete, name="questionnaire_delete"),
    url(r"^questionnaire/update_indices$", questionnaire_update_indices, name="questionnaire_update_indices"),

    url(r"^degrees/$", degree_index, name="degree_index"),

    url(r"^course_types/$", course_type_index, name="course_type_index"),
    url(r"^course_types/merge$", course_type_merge_selection, name="course_type_merge_selection"),
    url(r"^course_types/(\d+)/merge/(\d+)$", course_type_merge, name="course_type_merge"),

    url(r"^user/$", user_index, name="user_index"),
    url(r"^user/create$", user_create, name="user_create"),
    url(r"^user/import$", user_import, name="user_import"),
    url(r"^user/(\d+)/edit$", user_edit, name="user_edit"),

    url(r"^user/delete$", user_delete, name="user_delete"),
    url(r"^user/bulk_delete$", user_bulk_delete, name="user_bulk_delete"),
    url(r"^user/merge$", user_merge_selection, name="user_merge_selection"),
    url(r"^user/(\d+)/merge/(\d+)$", user_merge, name="user_merge"),

    url(r"^template/$", RedirectView.as_view(url='/staff/', permanent=True)),
    url(r"^template/(\d+)$", template_edit, name="template_edit"),

    url(r"faq/$", faq_index, name="faq_index"),
    url(r"faq/(\d+)$", faq_section, name="faq_section"),
]

urls.py
from django.conf import settings
from django.conf.urls import include, url
import django.views.static
import django.contrib.auth.views

from django.contrib import admin
admin.autodiscover()


urlpatterns = [
    url(r"^", include('evap.evaluation.urls')),
    url(r"^staff/", include('evap.staff.urls')),
    url(r"^results/", include('evap.results.urls')),
    url(r"^student/", include('evap.student.urls')),
    url(r"^contributor/", include('evap.contributor.urls')),
    url(r"^rewards/", include('evap.rewards.urls')),
    url(r"^grades/", include('evap.grades.urls')),

    url(r"^logout$", django.contrib.auth.views.logout, {'next_page': "/"}, name="django-auth-logout"),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r"^admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT})]

if settings.DEBUG and settings.ENABLE_DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]

evap/staff/templates/staff_course_comments.html
{% extends 'staff_course_base.html' %}

{% load evaluation_filters %}

{% block breadcrumb %}
    {{ block.super }}
    <li class="breadcrumb-item">{% trans 'Comments' %}</li>
{% endblock %}

{% block content %}
    {{ block.super }}

    <div class="d-flex">
        <h3 class="mr-auto">{{ course.name }} ({{ course.semester.name }})</h3>
        <div class="btn-switch btn-switch-light my-auto d-print-none">
            <div class="btn-switch-label">{% trans 'View' %}</div>
            <div class="btn-switch btn-group">
                <a href="{% url 'staff:course_comments' semester.id course.id %}" role="button" class="btn btn-sm btn-light{% if view == 'quick' %} active{% endif %}">
                    {% trans 'Quick' %}
                </a>
                <a href="{% url 'staff:course_comments' semester.id course.id %}?view=full" role="button" class="btn btn-sm btn-light{% if view == 'full' %} active{% endif %}">
                    {% trans 'Full' %}
                </a>
                <a href="{% url 'staff:course_comments' semester.id course.id %}?view=unreviewed" role="button" class="btn btn-sm btn-light{% if view == 'unreviewed' %} active{% endif %}">
                    {% trans 'Unreviewed' %}
                </a>
            </div>
        </div>
    </div>
    <div class="mb-2">
        {% if course.state == 'in_evaluation' %}
            <span class="badge badge-warning"><span class="fas fa-play icon-gray"></span> {% trans 'Still in evaluation' %}</span>
        {% else %}
            <span class="badge badge-light"><span class="fas fa-stop icon-green"></span> {% trans 'Evaluation finished' %}</span>
        {% endif %}
        {% include 'course_badges.html' with mode='manager' %}
    </div>
    <div class="bs-callout bs-callout-warning">
        {% blocktrans %}If you select "no" as publishing option for a text answer on this page, the respective answer will be deleted irrevocably when publishing the course's results. If you should edit an answer, the original answer will also be deleted when publishing the course's results.{% endblocktrans %}
    </div>
{% endblock %}

evap/staff/templates/staff_evaluation_textanswers_quick.html
{% extends 'staff_evaluation_textanswers.html' %}

{% block content %}
    {{ block.super }}

    <div class="modal fade" id="hotkeys-modal" tabindex="-1" role="dialog" aria-labelledby="hotkeys-modal-title" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="hotkeys-modal-title">Hotkeys</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <table class="modal-body table table-striped table-vertically-aligned">
                    <tr><td><kbd>←</kbd> <kbd>→</kbd></td><td>{% trans 'Navigate through answers' %}</td></tr>
                    <tr><td><kbd>J</kbd></td><td>{% trans 'Publish answer' %}</td></tr>
                    <tr><td><kbd>K</kbd></td><td>{% trans 'Make answer private to the contributor' %}</td></tr>
                    <tr><td><kbd>L</kbd></td><td>{% trans 'Remove answer' %}</td></tr>
                    <tr><td><kbd>&#x232b;</kbd></td><td>{% trans 'Unreview answer' %}</td></tr>
                    <tr><td><kbd>&#x21b2;</kbd></td><td>{% trans 'Review next evaluation' %}</td></tr>
                    <tr><td><kbd>N</kbd></td><td>{% trans 'Show all again' %}</td></tr>
                    <tr><td><kbd>M</kbd></td><td>{% trans 'Show unreviewed' %}</td></tr>
                </table>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <div class="card card-outline-primary slider">
        <div class="card-header">
            {% trans 'Text answers' %}
            <span class="hotkey-btn" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="{% trans 'Hotkeys' %}">
                <span class="far fa-keyboard" data-toggle="modal" data-target="#hotkeys-modal"></span>
            </span>
        </div>
        <div class="card-body slider-inner px-0">
            <div class="slider-side slider-side-left">
                <span class="badge badge-pill badge-primary" data-counter="reviewed-left" data-toggle="tooltip" data-placement="left" title="{% trans 'Reviewed text answers' %}"></span>
                <span class="fas fa-angle-left" data-slide="left"></span>
                <span class="badge badge-pill badge-secondary" data-counter="unreviewed-left" data-toggle="tooltip" data-placement="left" title="{% trans 'Unreviewed text answers' %}"></span>
            </div>
            <div class="slider-items">
                {% for questionnaire, contributor, label, is_responsible, results in sections %}
                    <div class="slider-item card-header" data-layer="0">
                        {{ questionnaire.public_name }}{% if contributor %}: {{ contributor.full_name }}{% if is_responsible %} ({% trans 'responsible' %}){% endif %}{% if label %} &ndash;&nbsp;<span class="font-italic">{{ label }}</span>{% endif %}{% endif %}
                    </div>
                    {% for result in results %}
                        <div class="slider-item card-body" data-layer="1">
                            {{ result.question.text}}
                        </div>
                        {% for answer in result.answers %}
                            <div class="slider-item card-body" data-layer="2" data-id="{{ answer.id }}"{% if contributor %} data-contribution="yes"{% endif %}
                                {% if answer.is_reviewed %}data-review="{% if answer.is_published %}publish{% elif answer.is_private %}make_private{% else %}hide{% endif %}"{% endif %}
                            >
                            <a class="textanswer-link" href="{% url 'staff:evaluation_textanswer_edit' semester.id evaluation.id answer.id %}">{{ answer.answer|linebreaksbr }}</a>
                            {% if answer.original_answer %}
                                <span class="textanswer-original">({{ answer.original_answer|linebreaksbr }})</span>
                            {% endif %}
                            </div>
                        {% endfor %}
                    {% endfor %}
                {% endfor %}
                <div class="slider-item alert text-center">
                    {% if sections %}
                        <span data-content="unreviewed">
                            {% trans 'Some text answers for this evaluation are still unreviewed.' %}
                        </span>
                        <span data-content="reviewed">
                            {% trans 'You have reviewed all text answers for this evaluation.' %}
                        </span>
                    {% else %}
                        <span>
                            {% trans 'There are no text answers for this evaluation.' %}
                        </span>
                    {% endif %}
                    {% if next_evaluation %}
                        <span>
                            {% blocktrans with name=next_evaluation.full_name count answers=next_evaluation.num_unreviewed_textanswers %}The next evaluation "{{ name }}" has got {{ answers }} unreviewed text answer.{% plural %}The next evaluation "{{ name }}" has got {{ answers }} unreviewed text answers.{% endblocktrans %}
                        </span>
                    {% endif %}
                </div>
            </div>
            <div class="slider-side slider-side-right">
                <span class="badge badge-pill badge-primary" data-counter="reviewed-right" data-toggle="tooltip" data-placement="right" title="{% trans 'Reviewed text answers' %}"></span>
                <span class="fas fa-angle-right" data-slide="right" title=""></span>
                <span class="badge badge-pill badge-secondary" data-counter="unreviewed-right" data-toggle="tooltip" data-placement="right" title="{% trans 'Unreviewed text answers' %}"></span>
            </div>
        </div>
        <div class="card-footer d-flex">
            <div class="lcr-left"></div>
            <div class="lcr-center" data-action-set="reviewing">
                <button role="button" data-action="publish" class="btn btn-sm btn-outline-secondary">
                    {% trans 'yes' %}
                </button>
                <button role="button" data-action="make_private" class="btn btn-sm btn-outline-secondary" disabled=""
                    title="{% blocktrans %}This answer is for a general question and can't be made private.{% endblocktrans %}" data-toggle="tooltip">
                    {% trans 'private' %}
                </button>
                <button role="button" data-action="hide" class="btn btn-sm btn-outline-secondary">
                    {% trans 'no' %}
                </button>
            </div>
            <div class="lcr-center d-none" data-action-set="summary">
                {% if next_evaluation %}
                    <a href="{% url 'staff:evaluation_textanswers' next_evaluation.course.semester.id next_evaluation.id %}" data-url="next-evaluation" class="btn btn-sm btn-primary">
                        {% trans 'Review next evaluation' %}
                    </a>
                {% endif %}
                <button role="button" data-startover="all" class="btn btn-sm btn-outline-primary">
                    {% trans 'Show all again' %}
                </button>
                <button role="button" data-startover="unreviewed" class="btn btn-sm btn-outline-primary">
                    {% trans 'Show unreviewed' %}
                </button>
            </div>
            <div class="lcr-right">
                <div data-action-set="reviewing">
                    <button role="button" data-action="unreview" class="btn btn-sm btn-outline-secondary">
                        {% trans 'unreview' %}
                    </button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block additional_javascript %}
    <script type="text/javascript">
        {% include "quick-review.js" %}
    </script>
{% endblock %}

evap/staff/templates/staff_semester_preparation_reminder.html
{% extends 'staff_semester_base.html' %}

{% load evaluation_filters %}

{% block breadcrumb %}
    {{ block.super }}
    <li class="breadcrumb-item">{% trans 'Preparation reminder' %}</li>
{% endblock %}

{% block content %}
    {{ block.super }}

    {% if responsible_list %}
        <div class="d-flex mb-3">
            <div class="mr-auto">
                <button type="button" id="remindAllButton" onClick="remindAllModalShow()" class="btn btn-sm btn-light">{% trans 'Remind all' %}</button>
            </div>
        </div>
    {% endif %}

    {% for responsible, evaluations, delegates in responsible_list %}
        <div class="card{% if not forloop.last %} mb-3{% endif %}">
            <div class="card-header d-flex">
                <span class="pl-1 mr-auto">
                    <a href="{% url 'staff:user_edit' responsible.id %}">{{ responsible.full_name }}</a>, {% trans 'Delegates' %}:
                    {% for delegate in delegates %}
                        <a href="{% url 'staff:user_edit' delegate.id %}">{{ delegate.full_name }}</a>{% if not forloop.last %},{% endif %}
                    {% empty %}
                        &mdash;
                    {% endfor %}
                </span>
                <div>
                    <a href="{% url 'staff:send_reminder' semester.id responsible.id %}" class="btn btn-sm btn-light">{% trans 'Send reminder' %}</a>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th style="width: 57%">{% trans 'Name' %}</th>
                            <th style="width: 18%">{% trans 'Start of evaluation' %}</th>
                            <th style="width: 25%">{% trans 'Last modified by' %}</th>
                       </tr>
                    </thead>
                    <tbody>
                        {% for evaluation in evaluations %}
                            <tr{% if evaluation.state != 'prepared' %} class="deactivate"{% endif %}>
                                <th scope="row">
                                    {% with approval_state_values=evaluation.state|approval_state_values %}
                                        <span class="{{ approval_state_values.icon }}" data-toggle="tooltip" data-placement="top" title="{{ approval_state_values.description }}"></span>
                                    {% endwith %}
                                    <a href="{% url 'staff:evaluation_edit' semester.id evaluation.id %}">{{ evaluation.full_name }}</a><br />
                                    {% include 'evaluation_badges.html' with mode='manager' %}
                                </th>
                                <td>{% include 'staff_evaluation_evaluation_period.html' with state=evaluation.state start_only=True %}</td>
                                <td>
                                    {% if evaluation.related_logentries.0.user %}
                                        {{ evaluation.related_logentries.0.user }} ({{ evaluation.related_logentries.0.datetime|date:"SHORT_DATETIME_FORMAT" }})
                                    {% else %}
                                        &mdash;
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endfor %}

{% endblock %}

{% block modals %}
    {{ block.super }}
    {% trans 'Remind all' as title %}
    {% trans 'Do you really want to remind everyone?' as question %}
    {% trans 'Remind all' as action_text %}
    {% include 'confirmation_modal.html' with modal_id='remindAllModal' title=title question=question action_text=action_text btn_type='primary' %}
    <script type="text/javascript">
        function remindAllModalAction() {
            var remindAllButton = $('#remindAllButton');
            remindAllButton.prop('disabled', true);
            remindAllButton.text('{% trans 'Reminding everyone' %}');

            $.ajax({
                type: "POST",
                url: "{% url 'staff:semester_preparation_reminder' semester_id=semester.id %}",
                success: function(){
                    location.reload();
                },
                error: function(){
                    window.alert("{% trans 'The server is not responding.' %}");
                }
            })
        }
    </script>
{% endblock %}

evap/staff/templates/staff_semester_todo.html
{% extends 'staff_semester_base.html' %}

{% load evaluation_filters %}

{% block breadcrumb %}
    {{ block.super }}
    <li class="breadcrumb-item">{% trans 'Todo' %}</li>
{% endblock %}

{% block content %}
    {{ block.super }}

    {% for responsible, evaluations, delegates in responsible_list %}
        <div class="card{% if not forloop.last %} mb-3{% endif %}">
            <div class="card-header d-flex">
                <span class="pl-1 mr-auto">
                    <a href="{% url 'staff:user_edit' responsible.id %}">{{ responsible.full_name }}</a>, {% trans 'Delegate' %}:
                    {% for delegate in delegates %}
                        <a href="{% url 'staff:user_edit' delegate.id %}">{{ delegate.full_name }}</a>{% if not forloop.last %},{% endif %}
                    {% empty %}
                        &mdash;
                    {% endfor %}
                </span>
                <div>
                    <a href="{% url 'staff:send_reminder' semester.id responsible.id %}" class="btn btn-sm btn-light">{% trans 'Send Reminder' %}</a>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th style="width: 40%">{% trans 'Name' %}</th>
                            <th style="width: 17%">{% trans 'State' %}</th>
                            <th style="width: 18%">{% trans 'Start of evaluation' %}</th>
                            <th style="width: 25%">{% trans 'Last modified by' %}</th>
                       </tr>
                    </thead>
                    <tbody>
                        {% for evaluation in evaluations %}
                            <tr{% if evaluation.state != 'prepared' %} class="deactivate"{% endif %}>
                                <th scope="row">
                                    <a href="{% url 'staff:evaluation_edit' semester.id evaluation.id %}">{{ evaluation.full_name }}</a><br />
                                    {% include 'evaluation_badges.html' with mode='manager' %}
                                </th>
                                <td>{{ evaluation.state|statename }}</td>
                                <td>{% include 'staff_evaluation_evaluation_period.html' with state=evaluation.state start_only=True %}</td>
                                <td>
                                    {% if evaluation.last_modified_user %}
                                        {{ evaluation.last_modified_user }}
                                    {% else %}
                                        &mdash;
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endfor %}

{% endblock %}